version: '3'

services:
  postgres:
    image: postgres:15.2-bullseye
    container_name: dev_database
    environment:
      POSTGRES_DB: pi
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: always

  backend:
    build: ./backend/
    container_name: dev_backend
    working_dir: /app
    ports:
      - '8000:8000'
    depends_on:
      - postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

  frontend:
    build: ./frontend/
    container_name: dev_frontend
    user: "node"
    working_dir: /app
    environment:
      - NODE_ENV=development
    ports:
      - '80:3000'
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data: