version: '3'

services:
  postgres:
    image: postgres:15.2-bullseye
    container_name: dev_database
    environment:
      POSTGRES_DB: pi
      POSTGRES_HOST_AUTH_METHOD: trust
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
#    networks:
#      - pi
    restart: always

  backend:
    build: ./backend/
    container_name: dev_backend
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000
    working_dir: /app
    ports:
      - '8000:8000'
    volumes:
      - .:/app
#    networks:
#      - pi
    depends_on:
      - postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

  frontend:
    build: ./frontend/
    container_name: dev_frontend
#    volumes:
#      - ./frontend:/home/node/app
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3000
    command: npm start

volumes:
  postgres_data:

networks:
  pi:
    name: pi
