version: '3'

services:
  web:
    build: .
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000
    working_dir: /app
    ports:
      - 8000:8000
    volumes:
      - .:/app
    networks:
      - pi
    depends_on:
      - postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

  postgres:
    image: postgres:15.2-bullseye
    environment:
      POSTGRES_DB: pi
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - pi
    restart: always

volumes:
  postgres_data:


networks:
  pi:
    name: pi
